jitsi-test
DanisHaertdinov/Hakaton-Lobby pull request #17
Opened 2022-10-26 16:27 UTC by DanisHaertdinov

2023-01-28 17:05 UTC, kicumkicum requested changes

2023-01-28 17:05 UTC, kicumkicum commented on src/pages/api/repo.ts
> +      return;
А почему тут происходит выход из функции? Понимаю, что скорее всего что-то пошло не так и данных не хватает, чтобы идти дальше, но по коду это не очевидно. Лучше добавить в лог описание, что не так.

К тому же, сервер ничего не ответит и для пользователя запрос повиснит

2023-01-28 17:05 UTC, kicumkicum commented on src/pages/index.tsx
> +      roomName: "JitsiMeetAPIE67xample",
Это не приватная информация?

2023-03-01 16:08 UTC, DanisHaertdinov commented on src/pages/index.tsx
> +      roomName: "JitsiMeetAPIE67xample",
спрятал

2023-03-01 16:13 UTC, DanisHaertdinov commented on src/pages/api/repo.ts
> +      return;
Пока что обернул в try catch, хотели переписать на next-connect вынес это в [ишью](https://github.com/DanisHaertdinov/Hakaton-Lobby/issues/18)

2023-03-01 16:38 UTC, kicumkicum approved these changes

2023-03-01 16:38 UTC, merged