setup github-oauth
DanisHaertdinov/Hakaton-Lobby pull request #20
Opened 2023-06-20 20:50 UTC by DanisHaertdinov

2023-06-21 15:53 UTC, kicumkicum requested changes
Есть несколько мелких моментов. В остальном норм 👍🏽

2023-06-28 15:47 UTC, DanisHaertdinov commented on src/pages/api/auth.ts
> +const gitHubSecret = process.env.GITHUB_OAuth_SECRET as string;
done

2023-06-28 15:47 UTC, DanisHaertdinov commented on src/pages/index.tsx
> +const gitHubID = process.env.GITHUB_OAuth_ID;
done

2023-06-28 15:48 UTC, DanisHaertdinov commented on src/pages/api/user/[id].ts
> +  return res.status(200).json(await getUserById(id));
done

2023-06-28 15:48 UTC, DanisHaertdinov commented on src/pages/api/user/User.ts
> +import { Octokit } from "octokit";
done

2023-06-28 15:48 UTC, DanisHaertdinov commented on src/pages/api/user/User.ts
> +import { Octokit } from "octokit";
done

2023-07-04 13:16 UTC, kicumkicum commented on src/config.ts
> +export const DOMAIN = process.env.VERCEL_URL || "localhost:3000";
А тут не нужно тайпкастить в `string`, как строчкой выше

2023-07-19 17:04 UTC, kicumkicum approved these changes

2023-07-19 17:04 UTC, merged