Config db
DanisHaertdinov/Hakaton-Lobby pull request #21
Opened 2024-02-28 16:03 UTC by DanisHaertdinov

2024-02-28 21:01 UTC, kicumkicum requested changes
Нормас!

2024-02-28 21:01 UTC, kicumkicum commented
Надо еще со сборкой разобраться

2024-10-16 17:55 UTC, DanisHaertdinov commented on src/endpoints/load.ts
> +  const response = await fetch(`http://${url}`, {
```suggestion
// TODO: вынести протокол в process.env.DOMAIN
  const response = await fetch(`http://${url}`, {
```

2024-10-16 17:56 UTC, DanisHaertdinov commented on src/endpoints/load.ts
> +// TODO: вынести протокол в process.env.DOMAIN
```suggestion
  // TODO: вынести протокол в process.env.DOMAIN
```

2024-10-16 18:01 UTC, DanisHaertdinov commented on src/pages/api/mongo/session/model.ts
> +export const Session = createMongoModel<SessionType>("Session", sessionSchema);
```suggestion
// TODO: перенести mongo из apo/mongo в src/service/mongo
export const Session = createMongoModel<SessionType>("Session", sessionSchema);
```

2024-10-16 18:03 UTC, DanisHaertdinov commented on src/pages/index.tsx
> +export const mongoConnect = async () => {
```suggestion
// TODO: вынести mongoConnect в src/services/mongo
export const mongoConnect = async () => {
```

2024-10-16 18:08 UTC, kicumkicum approved these changes

2024-10-16 18:08 UTC, merged