add coockies
DanisHaertdinov/Hakaton-Lobby pull request #4
Opened 2022-06-01 16:54 UTC by DanisHaertdinov

2022-06-04 20:59 UTC, kicumkicum requested changes
Едем дальше!

2022-06-04 20:59 UTC, kicumkicum commented on pages/api/hello.ts
> -// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
`pages` нужно перенести в `src`, но отдельным ПРом

2022-06-04 20:59 UTC, kicumkicum commented on pages/api/hello.ts
> +import { serialize } from "cookie";
Глобальную зависимость нужно поднять над локальными. Но лучше бы правило линтера

2022-06-04 20:59 UTC, kicumkicum commented on pages/api/hello.ts
> +    users: users,
Можно короче
```suggestion
    users,
```

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
>  interface props {
Тип с большой буквы

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
> +  const roomInput = useRef<Input>(null);
Больше подойдет `nicknameInput`

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
>      const responseJSON = await fetch(`/api/hello`, {
Записать в тех долг Вынести обращение к `fetch` из компонента, в модуль api

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
> +        // disabled={!nickname}
Наверно с рефом уже можно задесейблить

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
> +  const res = await fetch(`http://${DOMAIN}/api/hello`);
Нужно записать в тех долг Не делать запрос на самого себя, а использовать локальное обращение за данными. Я разобрался, примерно, почему не работало с переменной. Предложу костыльную эмуляция БД

2022-06-04 20:59 UTC, kicumkicum commented on src/types.ts
> +// Check vercel deploy
```suggestion
```

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
> +        onClick={() => handleButtonClick()}
Можно так, без создания доп функции
```suggestion
        onClick={handleButtonClick}
```

2022-06-04 20:59 UTC, kicumkicum commented on pages/index.tsx
> +  const handleButtonClick = async (): Promise<void> => {
В целом, ее можно в `useCallback` обернуть, чтобы лишних рендеров не было

2022-06-22 15:50 UTC, DanisHaertdinov commented on pages/index.tsx
> +  const handleButtonClick = async (): Promise<void> => {
done

2022-06-22 15:50 UTC, DanisHaertdinov commented on pages/index.tsx
> +        onClick={() => handleButtonClick()}
done

2022-06-22 15:51 UTC, DanisHaertdinov commented on pages/index.tsx
>  interface props {
done

2022-06-22 15:51 UTC, DanisHaertdinov commented on pages/api/hello.ts
> +    users: users,
done

2022-06-22 15:51 UTC, DanisHaertdinov commented on pages/api/hello.ts
> +import { serialize } from "cookie";
done

2022-06-22 17:45 UTC, merged